<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="cyl_radius" value="0.3"/><!-- Radius of the revolute joints -->
  <xacro:property name="cyl_height" value="0.3"/><!--  Height of the revolute joints -->
  <xacro:property name="l1" value="1" /> <!-- Link 1 --> <!-- arbitrary value for mass -->
  <xacro:property name="l2" value="1" /> <!-- Link 2 -->
  <xacro:property name="l3" value="1" /> <!-- Link 3 -->
  <xacro:property name="l4" value="1" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 ${cyl_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cyl_height}" radius = "${cyl_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${cyl_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cyl_height}" radius = "${cyl_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${cyl_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${(1/12)*mass*(cyl_height*cyl_height) + 1/4*mass*(cyl_height*cyl_height)}" ixy="0.0" ixz="0.0"
        iyy="${(1/12)*mass*(cyl_height*cyl_height) + 1/4*mass*(cyl_height*cyl_height)}" iyz="0.0"
        izz="${(1/2)*mass*cyl_radius*cyl_radius}"/>
      </inertial>
    </link>

    <joint name="joint1" type="continuous">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 ${cyl_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <link name="link1">
        <collision>
            <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${l1}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${l1}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
                ixx="${mass / 12.0 * (width*width + l1*l1)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (width*width + width*width)}" iyz="0.0"
                izz="${mass / 12.0 * (width*width + l1*l1)}"/>
        </inertial>
    </link>
    
    <joint name="fixed" type="fixed">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 0 ${l1}" rpy="0 0 0"/>
    </joint>
    
    <link name="link2">
        <collision>
            <origin xyz="${l1} 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${l2} ${width} ${width}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="${l1} 0 0" rpy="0 0 0"/>
           <geometry>
                <box size="${l2} ${width} ${width}"/>
           </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
            <mass value="${mass}"/>
            <inertia
                ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (width*width + l1*l1)}" iyz="0.0"
                izz="${mass / 12.0 * (width*width + l1*l1)}"/>
        </inertial>
    </link>
    
  </xacro:macro>

</robot>
